services:
  - type: web
    name: strapi
    env: node
    branch: backend-deploy 
    plan: starter
    buildCommand: cd backend && npm install && npm run build && ln -s /data/public/uploads ~/project/src/backend/public/uploads
    startCommand: cd backend && npm run start 
    healthCheckPath: /_health
    autoDeploy: false
    disk:
      name: strapi-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_FILENAME
        value: /data/strapi.db
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: NPM_CONFIG_IGNORE_SCRIPTS
        value: false